package edx12

var isaHeaderSpec = &X12Spec{
	Type:        SegmentSpec,
	Name:        isaSegmentId,
	Usage:       Required,
	Description: "Interchange control header",
	RepeatMax:   1,
	Label:       "header",
	Structure: []*X12Spec{
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA01",
			Usage:       Required,
			Description: "I01 authorization information qualifier",
			Label:       "authorizationQualifier",
			ValidCodes:  []string{"00", "03"},
			MinLength:   2,
			MaxLength:   2,
			DataType:    Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA02",
			Usage:       Required,
			Description: "I02 authorization information",
			Label:       "authorizationInformation",
			MinLength:   10,
			MaxLength:   10,
			DataType:    String,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA03",
			Usage:       Required,
			Description: "I03 security information qualifier",
			Label:       "securityInformationQualifier",
			ValidCodes:  []string{"00", "01"},
			MinLength:   2,
			MaxLength:   2,
			DataType:    Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA04",
			Usage:       Required,
			Description: "I04 security information",
			Label:       "securityInformation",
			MinLength:   10,
			MaxLength:   10,
			DataType:    String,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA05",
			Usage:       Required,
			Description: "I05 sender id qualifier",
			Label:       "senderIdQualifier",
			ValidCodes: []string{
				"14",
				"20",
				"27",
				"28",
				"29",
				"30",
				"33",
				"ZZ",
			},
			MinLength: 2,
			MaxLength: 2,
			DataType:  Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA06",
			Usage:       Required,
			Description: "I06 sender id",
			Label:       "senderId",
			MinLength:   15,
			MaxLength:   15,
			DataType:    String,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA07",
			Usage:       Required,
			Description: "I05 receiver id qualifier",
			Label:       "receiverIdQualifier",
			ValidCodes: []string{
				"14",
				"20",
				"27",
				"28",
				"29",
				"30",
				"33",
				"ZZ",
			},
			MinLength: 2,
			MaxLength: 2,
			DataType:  Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA08",
			Usage:       Required,
			Description: "I07 receiver id",
			Label:       "receiverId",
			MinLength:   15,
			MaxLength:   15,
			DataType:    String,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA09",
			Usage:       Required,
			Description: "I08 interchange date",
			Label:       "date",
			MinLength:   6,
			MaxLength:   6,
			DataType:    Date,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA10",
			Usage:       Required,
			Description: "I09 interchange time",
			Label:       "time",
			MinLength:   4,
			MaxLength:   4,
			DataType:    Time,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA11",
			Usage:       Required,
			Description: "I10 repetition separator",
			Label:       "repetitionSeparator",
			MinLength:   1,
			MaxLength:   1,
			DefaultVal:  "^",
			DataType:    String,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA12",
			Usage:       Required,
			Description: "I11 control version number",
			Label:       "controlVersionNumber",
			ValidCodes:  []string{"00501"},
			MinLength:   5,
			MaxLength:   5,
			DataType:    Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA13",
			Usage:       Required,
			Description: "I12 control number",
			Label:       "controlNumber",
			MinLength:   9,
			MaxLength:   9,
			DataType:    Numeric,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA14",
			Usage:       Required,
			Description: "I13 acknowledgment requested",
			Label:       "acknowledgmentRequested",
			ValidCodes:  []string{"0", "1"},
			MinLength:   1,
			MaxLength:   1,
			DataType:    Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA15",
			Usage:       Required,
			Description: "I14 interchange usage indicator",
			Label:       "usageIndicator",
			ValidCodes:  []string{"P", "T"},
			MinLength:   1,
			MaxLength:   1,
			DataType:    Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ISA16",
			Usage:       Required,
			Description: "I15 component element separator",
			Label:       "componentElementSeparator",
			MinLength:   1,
			MaxLength:   1,
			DefaultVal:  ":",
			DataType:    String,
		},
	},
}

var ieaTrailerSpec = &X12Spec{
	Type:        SegmentSpec,
	Name:        ieaSegmentId,
	Usage:       Required,
	Description: "Interchange control trailer",
	RepeatMax:   1,
	Label:       "trailer",
	Structure: []*X12Spec{
		&X12Spec{
			Type:        ElementSpec,
			Name:        "IEA01",
			Usage:       Required,
			Description: "I16 (number of functional groups)",
			Label:       "functionalGroupCount",
			MinLength:   1,
			MaxLength:   5,
			DataType:    Numeric,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "IEA02",
			Usage:       Required,
			Description: "I12 (interchange control number)",
			Label:       "controlNumber",
			MinLength:   9,
			MaxLength:   9,
			DataType:    Numeric,
		},
	},
}

var gsHeaderSpec = &X12Spec{
	Type:        SegmentSpec,
	Name:        gsSegmentId,
	Usage:       Required,
	Description: "Functional group header",
	RepeatMax:   1,
	Label:       "header",
	Structure: []*X12Spec{
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GS01",
			Usage:       Required,
			Description: "Functional identifier code",
			Label:       "functionalIdentifierCode",
			MinLength:   2,
			MaxLength:   2,
			DataType:    Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GS02",
			Usage:       Required,
			Description: "Application senders code",
			Label:       "applicationSenderCode",
			MinLength:   2,
			MaxLength:   15,
			DataType:    String,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GS03",
			Usage:       Required,
			Description: "Application receiver's code",
			Label:       "applicationReceiverCode",
			MinLength:   2,
			MaxLength:   15,
			DataType:    String,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GS04",
			Usage:       Required,
			Description: "Date",
			Label:       "date",
			MinLength:   8,
			MaxLength:   8,
			DataType:    Date,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GS05",
			Usage:       Required,
			Description: "Time",
			Label:       "time",
			MinLength:   4,
			MaxLength:   8,
			DataType:    Time,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GS06",
			Usage:       Required,
			Description: "Group control number",
			Label:       "controlNumber",
			MinLength:   1,
			MaxLength:   9,
			DataType:    Numeric,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GS07",
			Usage:       Required,
			Description: "Responsible agency code",
			Label:       "responsibleAgencyCode",
			ValidCodes:  []string{"X"},
			MinLength:   1,
			MaxLength:   2,
			DataType:    Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GS08",
			Usage:       Required,
			Description: "Version / release / industry identifier code",
			Label:       "versionCode",
			MinLength:   1,
			MaxLength:   12,
			DataType:    String,
		},
	},
}

var geTrailerSpec = &X12Spec{
	Type:        SegmentSpec,
	Name:        geSegmentId,
	Usage:       Required,
	Description: "Functional group trailer",
	RepeatMax:   1,
	Label:       "trailer",
	Structure: []*X12Spec{
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GE01",
			Usage:       Required,
			Description: "Number of transaction sets included",
			Label:       "transactionSetCount",
			MinLength:   1,
			MaxLength:   6,
			DataType:    Numeric,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "GE02",
			Usage:       Required,
			Description: "Group control number",
			Label:       "controlNumber",
			MinLength:   1,
			MaxLength:   9,
			DataType:    Numeric,
		},
	},
}

var stHeaderSpec = &X12Spec{
	Type:        SegmentSpec,
	Name:        stSegmentId,
	Usage:       Required,
	Description: "Transaction set header",
	RepeatMax:   1,
	Label:       "header",
	Structure: []*X12Spec{
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ST01",
			Usage:       Required,
			Description: "Transaction set identifier code",
			Label:       "transactionSetCode",
			ValidCodes: []string{
				"270",
				"271",
				"276",
				"277",
				"278",
				"820",
				"834",
				"835",
				"837",
				"997",
				"999",
			},
			MinLength: 3,
			MaxLength: 3,
			DataType:  Identifier,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ST02",
			Usage:       Required,
			Description: "Control number",
			Label:       "controlNumber",
			MinLength:   4,
			MaxLength:   9,
			DataType:    String,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "ST03",
			Usage:       Situational,
			Description: "Implementation convention reference",
			Label:       "versionCode",
			MinLength:   1,
			MaxLength:   35,
			DataType:    String,
		},
	},
}

var seTrailerSpec = &X12Spec{
	Type:        SegmentSpec,
	Name:        seSegmentId,
	Usage:       Required,
	Description: "Transaction set trailer",
	RepeatMax:   1,
	Label:       "trailer",
	Structure: []*X12Spec{
		&X12Spec{
			Type:        ElementSpec,
			Name:        "SE01",
			Usage:       Required,
			Description: "Number of included segments",
			Label:       "segmentCount",
			MinLength:   1,
			MaxLength:   10,
			DataType:    Numeric,
		},
		&X12Spec{
			Type:        ElementSpec,
			Name:        "SE02",
			Usage:       Required,
			Description: "Transaction set control number",
			Label:       "controlNumber",
			MinLength:   4,
			MaxLength:   9,
			DataType:    String,
		},
	},
}
